language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t raulvidal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raulvidal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-060971852699"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIAQ4MRUUONTHVM5YFN"
  secret_access_key: "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"
